############################################################
# +------------------------------------------------------+ #
# |                      ${name}                       | #
# +------------------------------------------------------+ #
############################################################

# Plugin created by SecretX (github.com/SecretX33)
# Version ${version}

# ${name} create Infernal Mobs according to `mobs.yml` file

# This file will NEVER get modified after being created, when updating the plugin please make sure you rename this one and let a new one be created, and copy your old configs to the new config file.

############################################################
# +------------------------------------------------------+ #
# |                   General Settings                   | #
# +------------------------------------------------------+ #
############################################################

# If false, particles effects for ALL things will be disabled GLOBALLY
enable-particle-effects: true
# Delay between infernal particles
delay-between-infernal-particles: 1.5   # in seconds
# Spread of infernal particles
infernal-particles-spread: 2.0          # in blocks
# Amount of particles spawned, this number greatly varies per particle, so I suggest you test it and manually adjust it to a balanced amount
amount-infernal-particles: 10           # in particles

# Display custom name mode, valid values are NONE, LOOKING_AT, ALWAYS; keep in mind that this option only affect new infernal mobs, the ones that already exist won't be affected by this change
display-infernal-custom-name-mode: LOOKING_AT

# If true, infernal mobs boss bar will be shown to the player's within configured range
enable-boss-bars: true
# Distance that the player has to be of an infernal mob in order to see its boss bar
boss-bar-show-range: 35.0

# If true, nearby players will be notified about the spawn of a new Infernal Mob with one of the spawn messages set on the `messages.yml` file
enable-inferno-spawn-messages: true
# The radius around the newly spawned infernal mob that a player has to be to receive the spawn message
inferno-spawn-message-radius: 30       # in blocks
# If true, nearby players will be notified about the death of a Infernal Mob with one of the spawn messages set on the `messages.yml` file
enable-inferno-death-messages: true
# The radius around the dead infernal mob that a player has to be to receive the death message
inferno-death-message-radius: 20       # in blocks

# Worlds in which mobs will have a chance of becoming infernal mobs; <ALL> is a special tag, it will allow the spawn of infernal mobs on ALL worlds; to prevent the spawn of infernals everywhere, just delete all the items and insert empty square brackets instead
worlds-in-which-infernal-mobs-can-spawn:
  - "<ALL>"

# Mobs spawned under reasons listed below will have a chance of becoming infernal mobs, see all spawn reasons here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html , Ctrl + F is your friend
spawn-reasons-which-infernal-mobs-can-spawn:
  - BEEHIVE                # When a bee is released from a beehive/bee nest
  - BREEDING               # When an animal breeds to create a child
  - BUILD_IRONGOLEM        # When an iron golem is spawned by being built
  - BUILD_SNOWMAN          # When an snowman is spawned by being built
  - BUILD_WITHER           # When an wither boss is spawned by being built
# - CURED                  # When a villager is cured from infection
# - CUSTOM                 # When a creature is spawned by plugins, may conflict with other plugins that also spawn mobs, disable if you notice strange behavior or compatibility errors
# - DEFAULT                # When an entity is missing a SpawnReason
# - DISPENSE_EGG           # When a creature is spawned by a dispenser dispensing an egg
  - DROWNED                # When a creature is spawned by another entity drowning
  - EGG                    # When a creature spawns from an egg
# - ENDER_PEARL            # When an entity is spawned as a result of ender pearl usage
# - EXPLOSION              # When eg an effect cloud is spawned as a result of a creeper exploding
  - INFECTION              # When a zombie infects a villager
# - JOCKEY                 # When an entity spawns as a jockey of another entity (mostly spider jockeys)
  - LIGHTNING              # When a creature spawns because of a lightning strike
  - MOUNT                  # When an entity spawns as a mount of another entity (mostly chicken jockeys)
  - NATURAL                # When something spawns from natural means
# - NETHER_PORTAL          # When a creature is spawned by nether portal
  - OCELOT_BABY            # When an ocelot has a baby spawned along with them
  - PATROL                 # When an entity is spawned as part of a patrol
  - RAID                   # When an entity is spawned as part of a raid
  - REINFORCEMENTS         # When an entity calls for reinforcements
# - SHEARED                # When an cow is spawned by shearing a mushroom cow
  - SHOULDER_ENTITY        # When an entity is spawned as a result of the entity it is being perched on jumping or being damaged
  - SILVERFISH_BLOCK       # When a silverfish spawns from a block
  - SLIME_SPLIT            # When a slime splits
# - SPAWNER                # When a creature spawns from a spawner, if enabled ALL spawners will have a chance of spawning infernal mobs
  - SPAWNER_EGG            # When a creature spawns from a Spawner Egg
  - TRAP                   # When an entity spawns as a trap for players approaching
# - VILLAGE_DEFENSE        # When an iron golem is spawned to defend a village
  - VILLAGE_INVASION       # When a zombie is spawned to invade a village


# Baby form of the mobs inside this list won't become infernals; to disable this blacklist, just delete all the items and insert empty square brackets instead
# Full list of mobs can be found here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html , Ctrl + F
blacklisted-baby-mob-types:
  - WOLF

# Which types of infernal mobs can spawn mounted onto another mob; to prevent all mobs from spawning mounted, just delete all the items and insert empty square brackets instead
# Full list of mobs can be found here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html , Ctrl + F
infernal-mobs-that-can-spawn-mounted:
  - DROWNED
  - ENDERMAN
  - EVOKER
  - HUSK
  - ILLUSIONER
  - PIG_ZOMBIE
  - PIGLIN
  - SKELETON
  - SNOWMAN
  - STRAY
  - VILLAGER
  - VINDICATOR
  - WITCH
  - WITHER_SKELETON
  - ZOMBIE
  - ZOMBIE_VILLAGER
  - ZOMBIFIED_PIGLIN

# Which types of mobs can become a mount for a mounted infernal mob; to disable all the mounts, just delete all the items and insert empty square brackets instead
# Full list of mobs can be found here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html , Ctrl + F
infernal-mobs-that-can-be-rided-by-another-infernal:
  - CHICKEN
  - COW
  - DONKEY
  - GHAST
  - HOGLIN
  - HORSE
  - LLAMA
  - MAGMA_CUBE
  - MULE
  - MUSHROOM_COW
  - PHANTOM
  - PIG
  - POLAR_BEAR
  - SHEEP
  - SKELETON_HORSE
  - SLIME
  - SPIDER
  - STRIDER
  - ZOGLIN
  - ZOMBIE_HORSE

############################################################
# +------------------------------------------------------+ #
# |                     Mob Abilities                    | #
# +------------------------------------------------------+ #
############################################################

# disable abilities you don't want mobs to have here by changing their value to 'false'
abilities:
  # if the mob is killed for the first time, it'll will respawn
  1up: true
  archer: true
  # mobs may spawns with enchanted armor, or protection buffs in case they cannot wear armor
  armoured: true
  berserk: true
  # mob hits may blind the player
  blinding: true
  bullwark: true
  cloaked: true
  confusion: true
  ender: true
  explode: true
  firework: true
  flying: true
  # shoots ghast fireballs
  ghastly: true
  ghost: true
  gravity: true
  lifesteal: true
  # mob have a small chance of spawning 3 babies next to it
  mama: true
  molten: true
  morph: true
  mounted: true
  necromancer: true
  # mob hits poisons the player
  poisonous: true
  potions: true
  quicksand: true
  rust: true
  hunger: true
  # mob will spawn with a random speed boost
  speedy: true
  storm: true
  thief: true
  tosser: true
  vengeance: true
  weakness: true
  webber: true
  # mob hits apply withering effect
  withering: true
