name: ${name}
version: ${version}
main: ${mainClass}
api-version: 1.16
authors: [SecretX]
description: Introduce Infernal Mobs, adding so much to any Survival Multiplayer experience.
website: https://github.com/SecretX33
softdepend: [WorldGuard]

commands:
  infernalmobsreloaded:
    description: ${name}
    usage: /<command> <sub> [parameters]
    aliases: [imr, imreloaded, mobs]

permissions:

  imr.*:
    description: Gives access to all ${name} commands. Default to players with op.
    default: op
    children:
      imr.reload: true
      imr.inspect: true

  imr.reload:
    description: Allows one to reload all plugin configurations.
    default: false

  imr.inspect:
    description: Allows one to inspect all entities and see what abilities they have.
    default: false

#  herbalism.create:
#    description: Allows one to create and destroy harvestable blocks, as well as use the selection stick.
#    default: false
#
#  herbalism.destroybyplace:
#    description: Allows one to destroy harvestable blocks by placing other block inside it.
#    default: false
#
#  herbalism.regen:
#    description: Allows one to use 'regen' and 'regenall' commands to regen the harvest blocks.
#    default: false
