name: ${name}
version: ${version}
main: ${mainClass}
api-version: 1.16
authors: [SecretX]
description: Introduce Infernal Mobs, adding so much to any Survival Multiplayer experience.
website: https://github.com/SecretX33
softdepend: [ProtocolLib, WorldGuard]

commands:
  imr:
    description: ${name}
    usage: /<command> <sub> [parameters]
    aliases: [infernalmobs, mobs]

permissions:

  imr.*:
    description: Gives access to all ${name} commands. Default to players with op.
    default: op
    children:
      imr.reload: true
      imr.inspect: true
      imr.spawn: true
      imr.multispawn: true
      imr.getloot: true

  imr.reload:
    description: Allows one to reload all plugin configurations.
    default: false

  imr.inspect:
    description: Allows one to inspect all entities and see what abilities they have.
    default: false

  imr.spawn:
    description: Allows one to spawn infernal mobs, optionally with specified abilities.
    default: false

  imr.multispawn:
    description: Allows one to spawn multiple infernal mobs at once, optionally with specified abilities.
    default: false

  imr.getloot:
    description: Allows player to use subcommand 'getloot', which allows him to get any loot item, in any amount.
    default: false
