name: ${name}
version: ${version}
main: ${mainClass}
api-version: 1.17
authors: [SecretX]
description: Introduce Infernal Mobs, adding so much to any Survival Multiplayer experience.
website: https://github.com/SecretX33
softdepend: [ProtocolLib, SilkSpawners, Towny, WorldGuard]

commands:
  imr:
    description: ${name}
    usage: /<command> <sub> [parameters]
    aliases: [infernalmobs, mobs]

permissions:

  imr.*:
    description: Gives access to all ${name} commands. Default to players with op.
    default: op
    children:
      imr.reload: true
      imr.inspect: true
      imr.spawn: true
      imr.multispawn: true
      imr.getloot: true
      imr.killall: true
      imr.charms.toggle: true
      imr.charms.toggle.break: true
      imr.charms.toggle.restore: true

  imr.reload:
    description: Allows one to reload all plugin configurations.
    default: false

  imr.inspect:
    description: Allows one to inspect all entities and see what abilities they have.
    default: false

  imr.spawn:
    description: Allows one to spawn infernal mobs, optionally with specified abilities.
    default: false

  imr.multispawn:
    description: Allows one to spawn multiple infernal mobs at once, optionally with specified abilities.
    default: false

  imr.getloot:
    description: Allows player to use subcommand 'getloot', which allows him to get any loot item, in any amount.
    default: false

  imr.killall:
    description: Allows player to use subcommand 'killall', which kill all infernals and their mounts from all worlds.
    default: false

  imr.charms.toggle:
    description: Allows player to use subcommand 'togglecharm', which toggles a charm between the broken and normal state.
    default: false

  imr.charms.toggle.break:
    description: Allows player to use subcommand 'togglecharm' to break a working charm.
    default: false

  imr.charms.toggle.restore:
    description: Allows player to use subcommand 'togglecharm' to fix a broken charm.
    default: false
